### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by airways** [mpartel/phpscheme#1]
Looks like a neat project, would like to incorporate it into some stuff I am working on. 

Can you set an open source license such as MIT for the project?

**Comment by mpartel** [comment]
MIT license set.

Feel free to use it but be aware that it's unmaintained, very slow, and rather incomplete. Only a very small subset of standard library functions have been implemented. Language features should be mostly there, except for macros.

It is quite simple though, so it should be pretty easy to extend and modify.

Overall, for an educational system at least, I think a properly sandboxed real scheme implementation would be a much more robust long-term solution. I don't know your exact use-case but you may be interested in https://github.com/testmycode/tmc-sandbox or something similar.
